# Generated by Django 6.0.1 on 2026-01-31 16:21

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_category', django_enum.fields.EnumCharField(choices=[('HISTORY_AND_PHYSICAL', 'History and Physical'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('PROGRESS_NOTE', 'Progress Note'), ('OTHER', 'Other')], max_length=20)),
                ('visit_status', django_enum.fields.EnumCharField(choices=[('PAY', 'Awaiting Visit Fee'), ('VIT', 'In Queue for Vitals'), ('CON', 'Awaiting Doctor Consultation'), ('INC', 'With Doctor'), ('LBP', 'Awaiting Lab Payment'), ('LBS', 'Awaiting Lab Sample'), ('LBR', 'Awaiting Lab Results'), ('REV', 'Awaiting Results Review'), ('FIN', 'Visit Finished'), ('CAN', 'Visit Cancelled'), ('OTH', 'Other')], max_length=3)),
                ('chief_complaint', models.TextField(blank=True)),
                ('current_status_since', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VisitStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_enum.fields.EnumCharField(choices=[('PAY', 'Awaiting Visit Fee'), ('VIT', 'In Queue for Vitals'), ('CON', 'Awaiting Doctor Consultation'), ('INC', 'With Doctor'), ('LBP', 'Awaiting Lab Payment'), ('LBS', 'Awaiting Lab Sample'), ('LBR', 'Awaiting Lab Results'), ('REV', 'Awaiting Results Review'), ('FIN', 'Visit Finished'), ('CAN', 'Visit Cancelled'), ('OTH', 'Other')], max_length=3)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='visits.visit')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('visit_category__in', ['HISTORY_AND_PHYSICAL', 'MEDICAL_CERTIFICATE', 'PROGRESS_NOTE', 'OTHER'])), name='visits_Visit_visit_category_VisitCategoryEnum'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('visit_status__in', ['PAY', 'VIT', 'CON', 'INC', 'LBP', 'LBS', 'LBR', 'REV', 'FIN', 'CAN', 'OTH'])), name='visits_Visit_visit_status_VisitStatusEnum'),
        ),
        migrations.AddConstraint(
            model_name='visitstatuslog',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PAY', 'VIT', 'CON', 'INC', 'LBP', 'LBS', 'LBR', 'REV', 'FIN', 'CAN', 'OTH'])), name='visits_VisitStatusLog_status_VisitStatusEnum'),
        ),
    ]
