# Generated by Django 6.0.1 on 2026-05-09 13:30

import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "visit_status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("AWAITING_INITIATION", "Awaiting to be initiated"),
                            ("AWAITING_CONSULTATION_PAYMENT", "Awaiting Visit Fee"),
                            (
                                "AWAITING_MISC_PAYMENT",
                                "Awaiting payment for misc charges",
                            ),
                            ("AWAITING_VITALS", "Awaiting Vitals"),
                            ("AWAITING_CONSULTATION", "Awaiting Doctor Consultation"),
                            ("IN_CONSULTATION", "With Doctor"),
                            ("AWAITING_LAB_PAYMENT", "Awaiting Lab Payment"),
                            ("AWAITING_LAB_SAMPLE", "Awaiting Lab Sample"),
                            ("IN_LAB", "In Lab"),
                            ("AWAITING_REVIEW", "Awaiting Lab Results Review"),
                            ("COMPLETED", "Completed"),
                            ("STALE", "Stale Visit"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="AWAITING_CONSULTATION_PAYMENT",
                        max_length=29,
                    ),
                ),
                (
                    "visit_category",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("HISTORY_AND_PHYSICAL", "History and Physical"),
                            ("MEDICAL_CERTIFICATE", "Medical Certificate"),
                            ("PROGRESS_NOTE", "Progress Note"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_status_since", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("assessment", models.TextField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="visits.visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("chief_complaint", models.TextField(blank=True, null=True)),
                ("history", models.TextField(blank=True, null=True)),
                ("assessment", models.TextField(blank=True, null=True)),
                (
                    "consulted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="visits.visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("AWAITING_INITIATION", "Awaiting to be initiated"),
                            ("AWAITING_CONSULTATION_PAYMENT", "Awaiting Visit Fee"),
                            (
                                "AWAITING_MISC_PAYMENT",
                                "Awaiting payment for misc charges",
                            ),
                            ("AWAITING_VITALS", "Awaiting Vitals"),
                            ("AWAITING_CONSULTATION", "Awaiting Doctor Consultation"),
                            ("IN_CONSULTATION", "With Doctor"),
                            ("AWAITING_LAB_PAYMENT", "Awaiting Lab Payment"),
                            ("AWAITING_LAB_SAMPLE", "Awaiting Lab Sample"),
                            ("IN_LAB", "In Lab"),
                            ("AWAITING_REVIEW", "Awaiting Lab Results Review"),
                            ("COMPLETED", "Completed"),
                            ("STALE", "Stale Visit"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=29,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitUpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_date", models.DateTimeField()),
                ("new_date", models.DateTimeField()),
                ("reason", models.CharField()),
                (
                    "new_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_to_visits_logs",
                        to="patients.patient",
                    ),
                ),
                (
                    "old_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_from_visits_logs",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_logs",
                        to="visits.visit",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.UniqueConstraint(
                fields=("patient", "date"), name="unique_patient_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "visit_status__in",
                        [
                            "AWAITING_INITIATION",
                            "AWAITING_CONSULTATION_PAYMENT",
                            "AWAITING_MISC_PAYMENT",
                            "AWAITING_VITALS",
                            "AWAITING_CONSULTATION",
                            "IN_CONSULTATION",
                            "AWAITING_LAB_PAYMENT",
                            "AWAITING_LAB_SAMPLE",
                            "IN_LAB",
                            "AWAITING_REVIEW",
                            "COMPLETED",
                            "STALE",
                            "CANCELLED",
                        ],
                    )
                ),
                name="visits_Visit_visit_status_VisitStatusEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "visit_category__in",
                        [
                            "HISTORY_AND_PHYSICAL",
                            "MEDICAL_CERTIFICATE",
                            "PROGRESS_NOTE",
                            "OTHER",
                        ],
                    )
                ),
                name="visits_Visit_visit_category_VisitCategoryEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="visitstatuslog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "AWAITING_INITIATION",
                            "AWAITING_CONSULTATION_PAYMENT",
                            "AWAITING_MISC_PAYMENT",
                            "AWAITING_VITALS",
                            "AWAITING_CONSULTATION",
                            "IN_CONSULTATION",
                            "AWAITING_LAB_PAYMENT",
                            "AWAITING_LAB_SAMPLE",
                            "IN_LAB",
                            "AWAITING_REVIEW",
                            "COMPLETED",
                            "STALE",
                            "CANCELLED",
                        ],
                    )
                ),
                name="visits_VisitStatusLog_status_VisitStatusEnum",
            ),
        ),
    ]
