# Generated by Django 6.0.1 on 2026-01-31 19:11

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='visit',
            name='visits_Visit_visit_status_VisitStatusEnum',
        ),
        migrations.RemoveConstraint(
            model_name='visitstatuslog',
            name='visits_VisitStatusLog_status_VisitStatusEnum',
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_status',
            field=django_enum.fields.EnumCharField(choices=[('PAY', 'Awaiting Visit Fee'), ('VIT', 'In Queue for Vitals'), ('CON', 'Awaiting Doctor Consultation'), ('INC', 'With Doctor'), ('LBP', 'Awaiting Lab Payment'), ('LBS', 'Awaiting Lab Sample'), ('REV', 'Awaiting Results Review'), ('FIN', 'Visit Finished'), ('CAN', 'Visit Cancelled'), ('OTH', 'Other')], editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='visitstatuslog',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('PAY', 'Awaiting Visit Fee'), ('VIT', 'In Queue for Vitals'), ('CON', 'Awaiting Doctor Consultation'), ('INC', 'With Doctor'), ('LBP', 'Awaiting Lab Payment'), ('LBS', 'Awaiting Lab Sample'), ('REV', 'Awaiting Results Review'), ('FIN', 'Visit Finished'), ('CAN', 'Visit Cancelled'), ('OTH', 'Other')], max_length=3),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('visit_status__in', ['PAY', 'VIT', 'CON', 'INC', 'LBP', 'LBS', 'REV', 'FIN', 'CAN', 'OTH'])), name='visits_Visit_visit_status_VisitStatusEnum'),
        ),
        migrations.AddConstraint(
            model_name='visitstatuslog',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PAY', 'VIT', 'CON', 'INC', 'LBP', 'LBS', 'REV', 'FIN', 'CAN', 'OTH'])), name='visits_VisitStatusLog_status_VisitStatusEnum'),
        ),
    ]
