# Generated by Django 6.0.1 on 2026-05-09 14:41

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        ("visits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="visit",
            name="visits_Visit_visit_status_VisitStatusEnum",
        ),
        migrations.RemoveConstraint(
            model_name="visitstatuslog",
            name="visits_VisitStatusLog_status_VisitStatusEnum",
        ),
        migrations.AlterField(
            model_name="visit",
            name="visit_status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("AWAITING_INITIATION", "Awaiting to be initiated"),
                    ("AWAITING_CONSULTATION_PAYMENT", "Awaiting Visit Fee"),
                    ("AWAITING_MISC_PAYMENT", "Awaiting payment for misc charges"),
                    ("AWAITING_VITALS", "Awaiting Vitals"),
                    ("AWAITING_CONSULTATION", "Awaiting Doctor Consultation"),
                    ("IN_CONSULTATION", "With Doctor"),
                    ("AWAITING_LAB_PAYMENT", "Awaiting Lab Payment"),
                    ("AWAITING_LAB_RESULT", "Awaiting Lab Results"),
                    ("IN_LAB", "In Lab"),
                    ("AWAITING_REVIEW", "Awaiting Lab Results Review"),
                    ("COMPLETED", "Completed"),
                    ("STALE", "Stale Visit"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="AWAITING_CONSULTATION_PAYMENT",
                max_length=29,
            ),
        ),
        migrations.AlterField(
            model_name="visitstatuslog",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("AWAITING_INITIATION", "Awaiting to be initiated"),
                    ("AWAITING_CONSULTATION_PAYMENT", "Awaiting Visit Fee"),
                    ("AWAITING_MISC_PAYMENT", "Awaiting payment for misc charges"),
                    ("AWAITING_VITALS", "Awaiting Vitals"),
                    ("AWAITING_CONSULTATION", "Awaiting Doctor Consultation"),
                    ("IN_CONSULTATION", "With Doctor"),
                    ("AWAITING_LAB_PAYMENT", "Awaiting Lab Payment"),
                    ("AWAITING_LAB_RESULT", "Awaiting Lab Results"),
                    ("IN_LAB", "In Lab"),
                    ("AWAITING_REVIEW", "Awaiting Lab Results Review"),
                    ("COMPLETED", "Completed"),
                    ("STALE", "Stale Visit"),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=29,
            ),
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "visit_status__in",
                        [
                            "AWAITING_INITIATION",
                            "AWAITING_CONSULTATION_PAYMENT",
                            "AWAITING_MISC_PAYMENT",
                            "AWAITING_VITALS",
                            "AWAITING_CONSULTATION",
                            "IN_CONSULTATION",
                            "AWAITING_LAB_PAYMENT",
                            "AWAITING_LAB_RESULT",
                            "IN_LAB",
                            "AWAITING_REVIEW",
                            "COMPLETED",
                            "STALE",
                            "CANCELLED",
                        ],
                    )
                ),
                name="visits_Visit_visit_status_VisitStatusEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="visitstatuslog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "AWAITING_INITIATION",
                            "AWAITING_CONSULTATION_PAYMENT",
                            "AWAITING_MISC_PAYMENT",
                            "AWAITING_VITALS",
                            "AWAITING_CONSULTATION",
                            "IN_CONSULTATION",
                            "AWAITING_LAB_PAYMENT",
                            "AWAITING_LAB_RESULT",
                            "IN_LAB",
                            "AWAITING_REVIEW",
                            "COMPLETED",
                            "STALE",
                            "CANCELLED",
                        ],
                    )
                ),
                name="visits_VisitStatusLog_status_VisitStatusEnum",
            ),
        ),
    ]
