# Generated by Django 6.0.1 on 2026-02-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_remove_visit_visits_visit_visit_status_visitstatusenum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='history',
            field=models.CharField(blank=True),
        ),
    ]
