# Generated by Django 6.0.1 on 2026-03-07 14:32

import datetime
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_visit_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.date(2026, 3, 7)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_status',
            field=django_enum.fields.EnumCharField(choices=[('PAY', 'Awaiting Visit Fee'), ('VIT', 'In Queue for Vitals'), ('CON', 'Awaiting Doctor Consultation'), ('INC', 'With Doctor'), ('LBP', 'Awaiting Lab Payment'), ('LBS', 'Awaiting Lab Sample'), ('REV', 'Awaiting Results Review'), ('FIN', 'Visit Finished'), ('CAN', 'Visit Cancelled'), ('OTH', 'Other')], max_length=3),
        ),
    ]
