# Generated by Django 6.0.1 on 2026-03-07 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_visit_date_alter_visit_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
