# Generated by Django 6.0.1 on 2026-05-09 13:30

import django.utils.timezone
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(max_length=100)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("MOBILE", "Mobile"),
                            ("GRACE_PERIOD", "Grace Period"),
                            ("WAIVER", "Waiver"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=12,
                    ),
                ),
                (
                    "payment_status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="CONFIRMED",
                        max_length=9,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
