# Generated by Django 6.0.1 on 2026-02-01 09:51

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0002_remove_visit_visits_visit_visit_status_visitstatusenum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', django_enum.fields.EnumCharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE', 'Mobile'), ('OTHER', 'Other')], default='CASH', max_length=6)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='visits.visit')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('payment_method__in', ['CASH', 'CARD', 'MOBILE', 'OTHER'])), name='payments_Payment_payment_method_PaymentMethodEnum')],
            },
        ),
    ]
