# Generated by Django 6.0.1 on 2026-02-11 15:32

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('visits', '0002_remove_visit_visits_visit_visit_status_visitstatusenum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=django_enum.fields.EnumCharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REFUNDED', 'Refunded')], default='CONFIRMED', max_length=9),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status__in', ['PENDING', 'CONFIRMED', 'REFUNDED'])), name='payments_Payment_payment_status_PaymentStatusEnum'),
        ),
    ]
