# Generated by Django 6.0.1 on 2026-05-09 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("charges", "0002_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustment",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="acceptor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recorded_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="charge",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="charges.charge",
            ),
        ),
        migrations.AddField(
            model_name="adjustment",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustments",
                to="payments.payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "payment_method__in",
                        ["CASH", "CARD", "MOBILE", "GRACE_PERIOD", "WAIVER", "OTHER"],
                    )
                ),
                name="payments_Payment_payment_method_PaymentMethodEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("payment_status__in", ["PENDING", "CONFIRMED", "REFUNDED"])
                ),
                name="payments_Payment_payment_status_PaymentStatusEnum",
            ),
        ),
    ]
