# Generated by Django 6.0.5 on 2026-06-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
