# Generated by Django 6.0.1 on 2026-02-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_charge_charged_by'),
        ('payments', '0002_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='visit',
        ),
        migrations.AddField(
            model_name='payment',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='charges.charge'),
        ),
    ]
