# Generated by Django 6.0.1 on 2026-02-01 09:51

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0002_remove_visit_visits_visit_visit_status_visitstatusenum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', django_enum.fields.EnumCharField(choices=[('CONSULTATION', 'Consultation'), ('LABORATORY', 'Laboratory'), ('PROCEDURE', 'Procedure'), ('MEDICATION', 'Medication'), ('OTHER', 'Other')], max_length=12)),
                ('description', models.TextField(blank=True, help_text='Description of the charge', null=True)),
                ('charge_status', django_enum.fields.EnumCharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('WAIVED', 'Wait')], max_length=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='visits.visit')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('charge_type__in', ['CONSULTATION', 'LABORATORY', 'PROCEDURE', 'MEDICATION', 'OTHER'])), name='charges_Charge_charge_type_ChargeTypeEnum'), models.CheckConstraint(condition=models.Q(('charge_status__in', ['PENDING', 'CANCELLED', 'WAIVED'])), name='charges_Charge_charge_status_ChargeStatusEnum')],
            },
        ),
    ]
