# Generated by Django 6.0.1 on 2026-05-09 13:30

import django.utils.timezone
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "charge_type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("CONSULTATION", "Consultation"),
                            ("LABORATORY", "Laboratory"),
                            ("PROCEDURE", "Procedure"),
                            ("MEDICATION", "Medication"),
                            ("MEDICAL_REPORT", "Medical Report"),
                            ("EQUIPMENT_AND_CONSUMABLES", "Equipment and Consumables"),
                            ("PENALTY", "Penalty"),
                            ("OTHER", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the charge", null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChargeOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
