# Generated by Django 6.0.1 on 2026-05-09 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("charges", "0001_initial"),
        ("lab_requests", "0001_initial"),
        ("visits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="lab_request",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charge",
                to="lab_requests.labrequest",
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charges",
                to="visits.visit",
            ),
        ),
        migrations.AddField(
            model_name="chargeoverride",
            name="charge",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charge_override",
                to="charges.charge",
            ),
        ),
        migrations.AddField(
            model_name="chargeoverride",
            name="overridden_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="charge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "charge_type__in",
                        [
                            "CONSULTATION",
                            "LABORATORY",
                            "PROCEDURE",
                            "MEDICATION",
                            "MEDICAL_REPORT",
                            "EQUIPMENT_AND_CONSUMABLES",
                            "PENALTY",
                            "OTHER",
                        ],
                    )
                ),
                name="charges_Charge_charge_type_ChargeTypeEnum",
            ),
        ),
    ]
