# Generated by Django 6.0.1 on 2026-01-31 16:21

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bp_systolic', models.IntegerField(blank=True, help_text='Systolic pressure in mmHg (the top number).', null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, help_text='Diastolic pressure in mmHg (the bottom number).', null=True)),
                ('pulse_rate', models.IntegerField(blank=True, help_text='Heart rate in beats per minute (BPM).', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Breaths per minute.', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Body temperature reading.', max_digits=5, null=True)),
                ('temperature_unit', django_enum.fields.EnumCharField(blank=True, choices=[('C', 'Celsius'), ('F', 'Fahrenheit'), ('K', 'Kelvin')], default='C', help_text='Scale used for the temperature reading.', max_length=1, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text="Patient's measured weight.", max_digits=5, null=True)),
                ('weight_unit', django_enum.fields.EnumCharField(blank=True, choices=[('K', 'Kg'), ('P', 'Lb'), ('O', 'Other')], default='K', help_text='Unit of measurement for weight.', max_length=1, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text="Patient's measured height.", max_digits=5, null=True)),
                ('height_unit', django_enum.fields.EnumCharField(blank=True, choices=[('M', 'M'), ('FT', 'Ft'), ('C', 'Cm'), ('O', 'Other')], default='M', help_text='Unit of measurement for height.', max_length=2, null=True)),
                ('spo2', models.DecimalField(blank=True, decimal_places=2, help_text='Oxygen saturation percentage (0-100).', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any distinct clinical observations or irregularities noted during measurement.')),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_vital_signs', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='visits.visit')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('temperature_unit__in', ['C', 'F', 'K']), ('temperature_unit__isnull', True), _connector='OR'), name='vital_signs_VitalSign_temperature_unit_TemperatureUnitEnum'), models.CheckConstraint(condition=models.Q(('weight_unit__in', ['K', 'P', 'O']), ('weight_unit__isnull', True), _connector='OR'), name='vital_signs_VitalSign_weight_unit_WeightUnitEnum'), models.CheckConstraint(condition=models.Q(('height_unit__in', ['M', 'FT', 'C', 'O']), ('height_unit__isnull', True), _connector='OR'), name='vital_signs_VitalSign_height_unit_HeightUnitEnum')],
            },
        ),
    ]
