# Generated by Django 6.0.1 on 2026-01-30 13:12

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_created_at_patient_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_unit', django_enum.fields.EnumCharField(blank=True, choices=[('C', 'Celsius'), ('F', 'Fahrenheit'), ('K', 'Kelvin'), ('other', 'Other')], default='C', max_length=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_unit', django_enum.fields.EnumCharField(blank=True, choices=[('kg', 'Kg'), ('lb', 'Pound'), ('other', 'Other')], default='kg', max_length=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_unit', django_enum.fields.EnumCharField(blank=True, choices=[('m', 'Meter'), ('feet', 'Feet'), ('inch', 'Inch'), ('cm', 'Centimeter'), ('other', 'Other')], default='m', max_length=5, null=True)),
                ('spo2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spo2_unit', django_enum.fields.EnumCharField(blank=True, choices=[('%', 'Percent'), ('other', 'Other')], default='%', max_length=5, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('temperature_unit__in', ['C', 'F', 'K', 'other']), ('temperature_unit__isnull', True), _connector='OR'), name='vital_signs_VitalSigns_temperature_unit_TemperatureUnitEnum'), models.CheckConstraint(condition=models.Q(('weight_unit__in', ['kg', 'lb', 'other']), ('weight_unit__isnull', True), _connector='OR'), name='vital_signs_VitalSigns_weight_unit_WeightUnitEnum'), models.CheckConstraint(condition=models.Q(('height_unit__in', ['m', 'feet', 'inch', 'cm', 'other']), ('height_unit__isnull', True), _connector='OR'), name='vital_signs_VitalSigns_height_unit_HeightUnitEnum'), models.CheckConstraint(condition=models.Q(('spo2_unit__in', ['%', 'other']), ('spo2_unit__isnull', True), _connector='OR'), name='vital_signs_VitalSigns_spo2_unit_Spo2UnitEnum')],
            },
        ),
    ]
