# Generated by Django 6.0.1 on 2026-01-30 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_created_at_patient_updated_at'),
        ('vital_signs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_vital_signs', to=settings.AUTH_USER_MODEL),
        ),
    ]
