# Generated by Django 6.0.1 on 2026-01-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0002_alter_vitalsigns_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='note',
            new_name='notes',
        ),
    ]
