# Generated by Django 6.0.1 on 2026-01-30 14:03

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('test_type', django_enum.fields.EnumCharField(choices=[('CATEGORICAL', 'Categorical'), ('NUMERICAL', 'Numerical')], max_length=11)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reference_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_requests.testgroup')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('test_type__in', ['CATEGORICAL', 'NUMERICAL'])), name='lab_requests_Test_test_type_TestTypeEnum')],
            },
        ),
    ]
