# Generated by Django 6.0.1 on 2026-05-09 13:30

import django.utils.timezone
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the semantic group ot tests/observations",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this test group active or archived?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Name of the test", max_length=100),
                ),
                (
                    "type",
                    django_enum.fields.EnumCharField(
                        choices=[("C", "Categorical"), ("N", "Numerical")], max_length=1
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this observation active?"
                    ),
                ),
                (
                    "unit_of_measurement",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement of the test",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "reference_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum value considered within the normal range; only used if this observation is numerical",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "reference_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum value considered within the normal range; only used if this observation is numerical",
                        max_digits=5,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this request active?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the billable lab service", max_length=100
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
