# Generated by Django 6.0.1 on 2026-01-31 16:21

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Is this request active?')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='patients.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='visits.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the test', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the test', max_digits=5, null=True)),
                ('test_type', django_enum.fields.EnumCharField(choices=[('C', 'Categorical'), ('N', 'Numerical')], max_length=1)),
                ('is_active', models.BooleanField(default=True, help_text='Is this test active?')),
                ('unit_of_measurement', models.CharField(blank=True, help_text='Unit of measurement of the test', max_length=100, null=True)),
                ('reference_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum value considered within the normal range', max_digits=5, null=True)),
                ('reference_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum value considered within the normal range', max_digits=5, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabRequestTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this request active?')),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='lab_requests.labrequest')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_request_tests', to='patients.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='lab_requests.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the group', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the tests in this group as an aggregate.', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Is this group active?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_test_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='test_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab_requests.testgroup'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('test_type__in', ['C', 'N'])), name='lab_requests_Test_test_type_TestTypeEnum'),
        ),
    ]
