# Generated by Django 6.0.1 on 2026-05-09 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab_requests", "0001_initial"),
        ("visits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="labgroup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_lab_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labobservation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_lab_observations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labobservation",
            name="lab_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_observations",
                to="lab_requests.labgroup",
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="ordered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_requests",
                to="visits.visit",
            ),
        ),
        migrations.AddField(
            model_name="labservice",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_lab_services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labservice",
            name="lab_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="lab_requests.labgroup"
            ),
        ),
        migrations.AddField(
            model_name="labservice",
            name="lab_observations",
            field=models.ManyToManyField(
                related_name="lab_services", to="lab_requests.labobservation"
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="lab_services",
            field=models.ManyToManyField(
                related_name="lab_requests", to="lab_requests.labservice"
            ),
        ),
        migrations.AddConstraint(
            model_name="labobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["C", "N"])),
                name="lab_requests_LabObservation_type_ObservationTypeEnum",
            ),
        ),
    ]
