# Generated by Django 6.0.1 on 2026-01-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labrequest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='labrequesttest',
            name='patient',
        ),
        migrations.AddField(
            model_name='labrequesttest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
