# Generated by Django 6.0.1 on 2026-02-08 08:20

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_requests', '0002_remove_labrequest_patient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the observation', max_length=100)),
                ('result_type', django_enum.fields.EnumCharField(choices=[('C', 'Categorical'), ('N', 'Numerical')], max_length=1)),
                ('is_active', models.BooleanField(default=True, help_text='Is this observation active?')),
                ('unit_of_measurement', models.CharField(blank=True, help_text='Unit of measurement of the test', max_length=100, null=True)),
                ('reference_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum value considered within the normal range', max_digits=5, null=True)),
                ('reference_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum value considered within the normal range', max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the test', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the test', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Is this test active?')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this request active?')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='labrequesttest',
            name='lab_request',
        ),
        migrations.RemoveField(
            model_name='labrequesttest',
            name='ordered_by',
        ),
        migrations.RemoveField(
            model_name='labrequesttest',
            name='test',
        ),
        migrations.RemoveConstraint(
            model_name='test',
            name='lab_requests_Test_test_type_TestTypeEnum',
        ),
        migrations.RemoveField(
            model_name='testgroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labrequest',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='labrequest',
            name='price',
        ),
        migrations.AddField(
            model_name='labobservation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labobservation',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='lab_requests.labtest'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='lab_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='lab_requests.labrequest'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='lab_requests.labtest'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LabRequestTest',
        ),
        migrations.RemoveField(
            model_name='test',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_group',
        ),
        migrations.AddConstraint(
            model_name='labobservation',
            constraint=models.CheckConstraint(condition=models.Q(('result_type__in', ['C', 'N'])), name='lab_requests_LabObservation_result_type_ResultTypeEnum'),
        ),
    ]
