# Generated by Django 6.0.1 on 2026-05-10 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_requests", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="labobservation",
            constraint=models.UniqueConstraint(
                fields=("name", "lab_group"), name="unique_name"
            ),
        ),
    ]
