# Generated by Django 6.0.1 on 2026-01-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_requests', '0002_labrequest_test_is_active_testgroup_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
