# Generated by Django 6.0.1 on 2026-01-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_requests', '0003_labrequest_is_active_labtestrequest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
