# Generated by Django 6.0.1 on 2026-02-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_requests', '0003_labobservation_labtest_labtestrequest_and_more'),
        ('lab_results', '0003_labtestresult_observationresult_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestGroup',
        ),
    ]
