# Generated by Django 6.0.1 on 2026-02-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_requests', '0004_delete_test_delete_testgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the test', max_digits=10),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
