# Generated by Django 6.0.1 on 2026-03-07 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_requests', '0005_alter_labtest_price_alter_labtestrequest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
