# Generated by Django 6.0.1 on 2026-05-09 13:30

import django.utils.timezone
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("strength", models.CharField(max_length=200)),
                (
                    "route",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("PO", "Orally"),
                            ("IV", "Intravenous"),
                            ("IM", "Intramuscular"),
                            ("SUBC", "Subcutaneous"),
                            ("TOP", "Topical"),
                            ("INHALATION", "Inhalation"),
                            ("OPH", "Ophthalmic"),
                            ("OTIC", "Otic"),
                            ("RECTAL", "Rectal"),
                            ("SUBLINGUAL", "Sublingual"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "frequency",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("QD", "Once per day"),
                            ("BID", "Twice per day"),
                            ("TID", "Three times per day"),
                            ("QID", "Four times per day"),
                            ("WEEKLY", "Once per week"),
                            ("BIWEEKLY", "Twice per week"),
                            ("PRN", "As needed"),
                            ("STAT", "Immediately"),
                        ],
                        max_length=8,
                    ),
                ),
                ("days", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
