# Generated by Django 6.0.1 on 2026-01-30 19:18

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_created_at_patient_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=200)),
                ('route', django_enum.fields.EnumCharField(choices=[('PO', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SUBCUTANEOUS', 'Subcutaneous'), ('TOPICAL', 'Topical'), ('INHALATION', 'Inhalation'), ('OPH', 'Ophthalmic'), ('OTIC', 'Otic'), ('RECTAL', 'Rectal'), ('SUBLINGUAL', 'Sublingual'), ('OTHER', 'Other')], max_length=12)),
                ('frequency', django_enum.fields.EnumCharField(choices=[('QD', 'Qd'), ('BID', 'Bid'), ('TID', 'Tid'), ('QID', 'Qid'), ('PRN', 'Prn'), ('STAT', 'Stat'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('OTHER', 'Other')], max_length=8)),
                ('days', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='prescriptions.prescription')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('route__in', ['PO', 'IV', 'IM', 'SUBCUTANEOUS', 'TOPICAL', 'INHALATION', 'OPH', 'OTIC', 'RECTAL', 'SUBLINGUAL', 'OTHER'])), name='prescriptions_Medication_route_RouteEnum'), models.CheckConstraint(condition=models.Q(('frequency__in', ['QD', 'BID', 'TID', 'QID', 'PRN', 'STAT', 'WEEKLY', 'BIWEEKLY', 'OTHER'])), name='prescriptions_Medication_frequency_FrequencyEnum')],
            },
        ),
    ]
