# Generated by Django 6.0.1 on 2026-01-31 16:21

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visits.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=200)),
                ('route', django_enum.fields.EnumCharField(choices=[('PO', 'Orally'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SUBC', 'Subcutaneous'), ('TOP', 'Topical'), ('INHALATION', 'Inhalation'), ('OPH', 'Ophthalmic'), ('OTIC', 'Otic'), ('RECTAL', 'Rectal'), ('SUBLINGUAL', 'Sublingual'), ('OTHER', 'Other')], max_length=10)),
                ('frequency', django_enum.fields.EnumCharField(choices=[('QD', 'Once per day'), ('BID', 'Twice per day'), ('TID', 'Three times per day'), ('QID', 'Four times per day'), ('WEEKLY', 'Once per week'), ('BIWEEKLY', 'Twice per week'), ('PRN', 'As needed'), ('STAT', 'Immediately')], max_length=8)),
                ('days', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='prescriptions.prescription')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('route__in', ['PO', 'IV', 'IM', 'SUBC', 'TOP', 'INHALATION', 'OPH', 'OTIC', 'RECTAL', 'SUBLINGUAL', 'OTHER'])), name='prescriptions_Medication_route_RouteEnum'), models.CheckConstraint(condition=models.Q(('frequency__in', ['QD', 'BID', 'TID', 'QID', 'WEEKLY', 'BIWEEKLY', 'PRN', 'STAT'])), name='prescriptions_Medication_frequency_FrequencyEnum')],
            },
        ),
    ]
