# Generated by Django 6.0.1 on 2026-05-09 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prescriptions", "0001_initial"),
        ("visits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="prescribed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prescribed_medications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="prescribed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="visits.visit"
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medications",
                to="prescriptions.prescription",
            ),
        ),
        migrations.AddConstraint(
            model_name="medication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "route__in",
                        [
                            "PO",
                            "IV",
                            "IM",
                            "SUBC",
                            "TOP",
                            "INHALATION",
                            "OPH",
                            "OTIC",
                            "RECTAL",
                            "SUBLINGUAL",
                            "OTHER",
                        ],
                    )
                ),
                name="prescriptions_Medication_route_RouteEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="medication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "frequency__in",
                        [
                            "QD",
                            "BID",
                            "TID",
                            "QID",
                            "WEEKLY",
                            "BIWEEKLY",
                            "PRN",
                            "STAT",
                        ],
                    )
                ),
                name="prescriptions_Medication_frequency_FrequencyEnum",
            ),
        ),
    ]
