# Generated by Django 6.0.1 on 2026-01-30 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_created_at_patient_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heent', models.TextField(blank=True, max_length=500, null=True)),
                ('chest', models.TextField(blank=True, max_length=500, null=True)),
                ('cardiovascular', models.TextField(blank=True, max_length=500, null=True)),
                ('abdomen', models.TextField(blank=True, max_length=500, null=True)),
                ('musculoskeletal', models.TextField(blank=True, max_length=500, null=True)),
                ('genitourinary', models.TextField(blank=True, max_length=500, null=True)),
                ('cns', models.TextField(blank=True, max_length=500, null=True)),
                ('miscellaneous', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_exams', to='patients.patient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_physical_exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
