# Generated by Django 6.0.1 on 2026-05-09 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhysicalExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "heent",
                    models.TextField(
                        blank=True, help_text="Head, Eye, Ear, Nose, and Throat"
                    ),
                ),
                ("chest", models.TextField(blank=True, help_text="Chest")),
                (
                    "cardiovascular",
                    models.TextField(blank=True, help_text="Cardiovascular"),
                ),
                ("abdomen", models.TextField(blank=True, help_text="Abdomen")),
                (
                    "musculoskeletal",
                    models.TextField(blank=True, help_text="Musculoskeletal"),
                ),
                (
                    "genitourinary",
                    models.TextField(blank=True, help_text="Genitourinary"),
                ),
                (
                    "cns",
                    models.TextField(blank=True, help_text="Central nervous system"),
                ),
                (
                    "miscellaneous",
                    models.TextField(blank=True, help_text="Miscellaneous"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
