# Generated by Django 6.0.1 on 2026-01-31 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heent', models.TextField(blank=True, help_text='Head, Eye, Ear, Nose, and Throat')),
                ('chest', models.TextField(blank=True, help_text='Chest')),
                ('cardiovascular', models.TextField(blank=True, help_text='Cardiovascular')),
                ('abdomen', models.TextField(blank=True, help_text='Abdomen')),
                ('musculoskeletal', models.TextField(blank=True, help_text='Musculoskeletal')),
                ('genitourinary', models.TextField(blank=True, help_text='Genitourinary')),
                ('cns', models.TextField(blank=True, help_text='Central nervous system')),
                ('miscellaneous', models.TextField(blank=True, help_text='Miscellaneous')),
                ('is_active', models.BooleanField(default=True)),
                ('examined_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_exams_examined', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_exams', to='patients.patient')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_exams', to='visits.visit')),
            ],
        ),
    ]
