# Generated by Django 6.0.1 on 2026-01-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalexam',
            name='patient',
        ),
    ]
