# Generated by Django 6.0.1 on 2026-01-31 16:21

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text='First name of the patient', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the patient', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Date of birth of the patient')),
                ('sex', django_enum.fields.EnumCharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the patient', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height of the patient', max_digits=5, null=True)),
                ('region', django_enum.fields.EnumCharField(choices=[('ADDIS_ABABA', 'Addis Ababa'), ('AFAR', 'Afar'), ('AMHARA', 'Amhara'), ('BENISHANGUL_GUMUZ', 'Benishangul Gumuz'), ('CENTRAL_ETHIOPIA', 'Central Ethiopia'), ('DIRE_DAWA', 'Dire Dawa'), ('GAMBELA', 'Gambela'), ('HARARI', 'Harari'), ('OROMIA', 'Oromia'), ('SIDAMA', 'Sidama'), ('SOMALI', 'Somali'), ('SOUTH_ETHIOPIA', 'South Ethiopia'), ('SOUTH_WEST_ETHIOPIA', 'South West Ethiopia'), ('TIGRAY', 'Tigray'), ('OTHER', 'Other')], help_text='Region where patient resides', max_length=19)),
                ('city', models.CharField(help_text='City where the patient resides', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the patient is active. Used for soft deletes ')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('sex__in', ['M', 'F'])), name='patients_Patient_sex_SexEnum'), models.CheckConstraint(condition=models.Q(('region__in', ['ADDIS_ABABA', 'AFAR', 'AMHARA', 'BENISHANGUL_GUMUZ', 'CENTRAL_ETHIOPIA', 'DIRE_DAWA', 'GAMBELA', 'HARARI', 'OROMIA', 'SIDAMA', 'SOMALI', 'SOUTH_ETHIOPIA', 'SOUTH_WEST_ETHIOPIA', 'TIGRAY', 'OTHER'])), name='patients_Patient_region_RegionEnum')],
            },
        ),
    ]
