# Generated by Django 6.0.1 on 2026-02-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the patient is active. Used for soft deletes'),
        ),
    ]
