# Generated by Django 6.0.1 on 2026-02-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, help_text="Patient's phone number", max_length=10, null=True),
        ),
    ]
