# Generated by Django 6.0.1 on 2026-02-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, help_text="Patient's phone number", max_length=20, null=True),
        ),
    ]
